# Generated by Django 5.0 on 2023-12-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('cover_image', models.CharField(max_length=500)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('min_playtime', models.IntegerField()),
                ('max_playtime', models.IntegerField()),
                ('categories', models.CharField(max_length=500)),
                ('cooperative', models.BooleanField()),
                ('rating', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('year_published', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('abstracts_rank', models.IntegerField()),
                ('cgs_rank', models.IntegerField()),
                ('childrens_games_rank', models.IntegerField()),
                ('family_games_rank', models.IntegerField()),
                ('party_games_rank', models.IntegerField()),
                ('strategy_games_rank', models.IntegerField()),
                ('thematic_rank', models.IntegerField()),
                ('wargames_rank', models.IntegerField()),
            ],
        ),
    ]
