# Generated by Django 5.0 on 2023-12-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgamebuddy_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='description',
            field=models.CharField(max_length=100000),
        ),
        migrations.CreateModel(
            name='UserBoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_game_id', models.ManyToManyField(to='boardgamebuddy_api.boardgame')),
                ('user_id', models.ManyToManyField(to='boardgamebuddy_api.user')),
            ],
        ),
    ]
