# Generated by Django 5.0 on 2023-12-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgamebuddy_api', '0002_user_alter_boardgame_description_userboardgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='abstracts_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='categories',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='cgs_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='childrens_games_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='cooperative',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='cover_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='description',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='family_games_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_players',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_playtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_players',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_playtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='party_games_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='strategy_games_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='thematic_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='wargames_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='year_published',
            field=models.IntegerField(null=True),
        ),
    ]
