# Generated by Django 5.0 on 2023-12-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgamebuddy_api', '0004_remove_boardgame_cooperative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='cooperative',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
